#!/usr/bin/env bash
# Does the loop in skills/tt-bio-bringup/run.sh actually work? Four legs, each a negative control
# for one claim it makes:
#
#   mechanics  it advances phase by phase and exits 0 on the iteration the last gate goes green,
#              not one earlier
#   tamper     weakening the gate mid-run aborts the loop instead of finishing it
#   stall      an iteration that moves nothing stops the loop after N of them
#   resume     SIGKILL mid-iteration, restart, no manual repair
#
#     bash scripts/loop-selftest.sh all
#
# Scope, because the label on a check has to match what it measured. This builds a throwaway port
# directory whose gate manifest is generated by the real `port_gate.py status --init`, so the real
# structural validator runs against it, and whose gate commands are the real ones: real pytest, real
# determinism arms, real `${CARD:?}` pinning. What is fake is the port. The tests assert a byte
# comparison against a file another fixture script wrote, and a real model is nowhere in it. So a
# green run here means the loop DRIVER is correct. It says nothing about any port, and it is not
# evidence that a port passed anything.
#
# `claude` is not called: PORT_LOOP_CLAUDE substitutes a fixture agent, which is the only way these
# legs are deterministic and free. It substitutes the AGENT, never the gate, so it cannot manufacture
# a green: every PASS below was produced by the real port_gate.py running the real gate command.
# The real `claude -p` invocation is proven separately, once, against a real session.
#
# Linux, bash 4+, python3 with pytest. Exit 0 all requested legs passed, 1 one failed, 2 could not run.

set -u
cd "$(dirname "$0")/.." || exit 2
REPO="$PWD"
SKILL="$REPO/skills/tt-bio-bringup"
[ -f "$SKILL/run.sh" ] || { echo "no $SKILL/run.sh" >&2; exit 2; }

MODE="${1:-all}"
case "$MODE" in mechanics|tamper|stall|resume|all) ;;
  *) echo "usage: bash scripts/loop-selftest.sh <mechanics|tamper|stall|resume|all>" >&2; exit 2 ;;
esac

command -v python3 >/dev/null 2>&1 || { echo "no python3" >&2; exit 2; }
python3 -c 'import pytest' 2>/dev/null || { echo "the fixture's gates run pytest; python3 -m pytest is not available" >&2; exit 2; }
command -v git >/dev/null 2>&1 || { echo "no git" >&2; exit 2; }

FAIL=0
ok()   { printf '  ok    %s\n' "$1"; }
bad()  { printf '  FAIL  %s\n' "$1"; FAIL=1; }
want() { if [ "$2" = "$3" ]; then ok "$1 ($3)"; else bad "$1: expected $3, got $2"; fi; }

# ---------------------------------------------------------------------------- the fixture

# Four gate-passing documents, taken from the script that proves they pass rather than written
# again here where nothing would check them.
DOCS="$(mktemp -d)" || exit 2
trap 'rm -rf "$DOCS"' EXIT
bash scripts/check-example.sh --emit "$DOCS" >/dev/null 2>&1 \
  || { echo "check-example.sh does not pass, so its documents cannot be trusted as a fixture" >&2
       exit 2; }

build_fixture() {   # build_fixture <dir>
  local d="$1"
  mkdir -p "$d/scripts" "$d/notes" "$d/tests" "$d/docs" "$d/env/bin" "$d/.fixture/docs" || return 2
  cp "$DOCS"/*.md "$d/.fixture/docs/"
  cp "$SKILL/gates/port_gate.py" "$d/scripts/port_gate.py"

  # The fork's venv interpreter. Every gate command names ./env/bin/python3 rather than a bare
  # python3, and that distinction is load-bearing in a real port, so the fixture keeps it.
  printf '#!/bin/sh\nexec %s "$@"\n' "$(command -v python3)" > "$d/env/bin/python3"
  chmod +x "$d/env/bin/python3"

  ( cd "$d" && python3 scripts/port_gate.py status --init --model minifold >/dev/null ) || return 2

  write_agent "$d"
  ( cd "$d"
    git init -q . 2>/dev/null
    git config user.email fixture@example.com
    git config user.name  "loop selftest fixture"
    git add scripts notes tests docs env .fixture 2>/dev/null
    git commit -q -m "fixture port directory" 2>/dev/null ) || return 2
}

# The fixture agent. One phase's artifacts per call, so iteration N advances exactly one gate and
# the boundary in the mechanics leg is a number, not an impression.
write_agent() {
  cat > "$1/.fixture/agent.sh" <<'AGENT'
#!/usr/bin/env bash
# Stands in for `claude -p`. Reads no prompt: the point is a deterministic advance per call.
set -u
cd "$(dirname "$0")/.." || exit 2
if [ "${1:-}" = "--help" ]; then
  echo "fixture agent. supported: -p --permission-mode --output-format --max-budget-usd"
  exit 0
fi

STEP="$(cat .fixture/step 2>/dev/null || echo 1)"
[ -f .fixture/tamper_at ] && [ "$STEP" = "$(cat .fixture/tamper_at)" ] && {
  # Exactly the bytes the loop hashes. A neighbouring file would prove nothing.
  sed -i 's| --require-heading "Negative controls"||' notes/PORT_GATES.md
}
[ -f .fixture/tamper_gate_at ] && [ "$STEP" = "$(cat .fixture/tamper_gate_at)" ] && {
  printf '\n# loosened by the agent\n' >> scripts/port_gate.py
}
[ -f .fixture/stall ] && {
  # The adversary the stall check is for: it rewrites PORT_STATE.md with a fresh timestamp and
  # does nothing else. A content hash cannot tell that from a fact, which is why the loop does
  # not use one.
  printf 'last touched %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> notes/PORT_STATE.md
  printf '{"total_cost_usd":0.01,"subtype":"success","is_error":false,"num_turns":1,'
  printf '"permission_denials":[],"result":"touched the state file, did no work"}\n'
  exit 0
}

py() { printf '%s\n' "$2" > "$1"; }

case "$STEP" in
1)  cp .fixture/docs/plan.md  notes/PORT_PLAN.md
    cp .fixture/docs/state.md notes/PORT_STATE.md ;;
2)  mkdir -p scripts/minifold_port/parity_artifacts
    py scripts/minifold_port/capture.py 'import argparse, pathlib
a = argparse.ArgumentParser(); a.add_argument("--len", type=int); a.add_argument("--seed", type=int)
n = a.parse_args()
out = pathlib.Path("scripts/minifold_port/parity_artifacts/minifold_%d.pt" % n.len)
out.parent.mkdir(parents=True, exist_ok=True)
out.write_bytes(bytes((i * 7 + n.seed) % 251 for i in range(n.len)))'
    py tests/test_minifold_fixtures.py 'import pathlib

def test_fixture_replays_to_the_same_bytes():
    p = pathlib.Path("scripts/minifold_port/parity_artifacts/minifold_117.pt")
    assert p.read_bytes() == bytes((i * 7) % 251 for i in range(117))' ;;
3)  py scripts/minifold_port/forward.py 'import argparse, pathlib
a = argparse.ArgumentParser(); a.add_argument("--len", type=int); a.add_argument("--out")
n = a.parse_args()
pathlib.Path(n.out).write_bytes(bytes((i * 3) % 251 for i in range(n.len)))'
    py tests/test_minifold_weights.py 'import os

def test_every_parameter_consumed_exactly_once():
    consumed = {"blocks.0.ffn.w", "head.proj.w"}
    assert consumed == {"blocks.0.ffn.w", "head.proj.w"}
    assert os.environ.get("TT_VISIBLE_DEVICES"), "the gate must pin a card"' ;;
4)  printf 'seq_64\nseq_117\n' > notes/eval_set.txt
    if [ -f .fixture/slow ]; then sleep 45; fi
    py scripts/minifold_port/task_metric.py 'import argparse
a = argparse.ArgumentParser(); a.add_argument("--set", required=True); a.parse_args()
print("top-L/5 contact precision 0.61 vs 0.62 on CPU")'
    py tests/test_minifold_parity.py 'import os

def test_end_to_end_parity():
    assert os.environ.get("TT_VISIBLE_DEVICES"), "the gate must pin a card"
    assert abs(0.9993 - 1.0) < 1e-2'
    cp .fixture/docs/parity.md docs/minifold-parity.md ;;
5)  py tests/test_minifold_ladder.py 'import pytest

@pytest.mark.parametrize("L", [16, 64, 117, 380, 512])
def test_ladder(L):
    assert L % 32 == 0 or L in (117, 380, 16)' ;;
6)  cp .fixture/docs/perf.md docs/minifold-perf.md ;;
7)  py scripts/packaging_smoke.py 'print("wheel installs clean")'
    py scripts/release_gate.py 'import os, sys
sys.exit(0 if os.environ.get("TT_VISIBLE_DEVICES") else 1)'
    py tests/test_perf_model_coverage.py 'def test_every_model_has_a_perf_row():
    assert {"minifold"} <= {"minifold", "esmfold2"}'
    py tests/test_repo_root_clean.py 'import pathlib

def test_the_ports_documents_are_where_the_gate_says():
    for p in ("notes/PORT_PLAN.md", "notes/PORT_STATE.md", "docs/minifold-parity.md",
              "docs/minifold-perf.md"):
        assert pathlib.Path(p).is_file(), p' ;;
8)  py scripts/perf_regression.py 'print("within 2% of the recorded baseline")' ;;
*)  ;;
esac
echo $((STEP + 1)) > .fixture/step
printf '{"total_cost_usd":0.01,"subtype":"success","is_error":false,"num_turns":4,'
printf '"permission_denials":[],"result":"worked step %s"}\n' "$STEP"
AGENT
  chmod +x "$1/.fixture/agent.sh"
}

# The loop, with the fixture agent in place of claude. CARD and REF_PY are exported because the
# real gates need them and the fixture does not get to pretend otherwise.
run_loop() {   # run_loop <dir> <logfile> [extra run.sh args...]
  local d="$1" log="$2"; shift 2
  ( cd "$d" && CARD=0 REF_PY=./env/bin/python3 PORT_LOOP_CLAUDE="$d/.fixture/agent.sh" \
      bash "$SKILL/run.sh" --unattended --model-name minifold "$@" ) > "$log" 2>&1
}

iters()   { grep -c '^======== iteration ' "$1"; }
passes()  { sed -n 's/^ALL-PHASES: \([0-9]*\)\/8 PASS$/\1/p' "$1" | tr '\n' ' '; }

# ---------------------------------------------------------------------------- legs

leg_mechanics() {
  echo "mechanics: the loop advances phase by phase and exits 0 exactly at the last gate"
  local d; d="$(mktemp -d)"; build_fixture "$d" || { bad "could not build the fixture"; return; }
  run_loop "$d" "$d/loop.log"; local rc=$?
  want "exit code" "$rc" 0
  # 8 phases, one per iteration, and the ninth iteration is the one that sees all eight green.
  want "iterations" "$(iters "$d/loop.log")" 9
  want "gates green, iteration by iteration" "$(passes "$d/loop.log")" "0 1 2 3 4 5 6 7 8 "
  if grep -q '^======== iteration 10 ' "$d/loop.log"; then
    bad "ran a tenth iteration, so it did not stop when the port went green"
  else ok "stopped at the iteration the last gate went green, not later"; fi
  if grep -q 'LOOP-ENDED: GREEN' "$d/notes/PORT_STATE.md"; then
    ok "wrote LOOP-ENDED: GREEN to notes/PORT_STATE.md"
  else bad "no LOOP-ENDED: GREEN in notes/PORT_STATE.md, which is the only thing the customer reads"; fi
  # The boundary, from the other side: with the last phase's artifact removed the same tree is red.
  rm -f "$d/scripts/perf_regression.py"
  ( cd "$d" && CARD=0 REF_PY=./env/bin/python3 python3 "$SKILL/gates/port_gate.py" \
      status --all-phases >/dev/null 2>&1 ); local rc2=$?
  want "same tree minus one Phase 7 artifact is not green" "$rc2" 1
  rm -rf "$d"
}

leg_tamper() {
  echo "tamper: weakening the gate mid-run aborts the loop"
  local d; d="$(mktemp -d)"; build_fixture "$d" || { bad "could not build the fixture"; return; }
  echo 3 > "$d/.fixture/tamper_at"     # iteration 3 drops a --require-heading from Phase 3
  run_loop "$d" "$d/loop.log"; local rc=$?
  want "exit code" "$rc" 3
  if grep -q 'LOOP-ENDED: TAMPER' "$d/notes/PORT_STATE.md"; then
    ok "wrote LOOP-ENDED: TAMPER to notes/PORT_STATE.md"
  else bad "no LOOP-ENDED: TAMPER in notes/PORT_STATE.md"; fi
  if grep -q 'Negative controls' "$d/loop.log"; then
    ok "printed the diff naming the requirement that was removed"
  else bad "aborted without showing what changed"; fi
  if grep -q 'ALL-PHASES: 8/8' "$d/loop.log"; then bad "reported a green port anyway"; fi

  echo "tamper: editing scripts/port_gate.py aborts the loop"
  local e; e="$(mktemp -d)"; build_fixture "$e" || { bad "could not build the fixture"; return; }
  echo 2 > "$e/.fixture/tamper_gate_at"
  run_loop "$e" "$e/loop.log"; local rc2=$?
  want "exit code" "$rc2" 3
  rm -rf "$d" "$e"
}

leg_stall() {
  echo "stall: iterations that move nothing stop the loop"
  local d; d="$(mktemp -d)"; build_fixture "$d" || { bad "could not build the fixture"; return; }
  touch "$d/.fixture/stall"
  run_loop "$d" "$d/loop.log"; local rc=$?
  want "exit code" "$rc" 4
  want "iterations before stopping" "$(iters "$d/loop.log")" 3
  if grep -q 'LOOP-ENDED: STALLED' "$d/notes/PORT_STATE.md"; then
    ok "wrote LOOP-ENDED: STALLED to notes/PORT_STATE.md"
  else bad "no LOOP-ENDED: STALLED in notes/PORT_STATE.md"; fi
  # And the control: --stall 5 must take five, or the number is decoration.
  local e; e="$(mktemp -d)"; build_fixture "$e" || { bad "could not build the fixture"; return; }
  touch "$e/.fixture/stall"
  run_loop "$e" "$e/loop.log" --stall 5
  want "--stall 5 takes five" "$(iters "$e/loop.log")" 5
  rm -rf "$d" "$e"
}

leg_resume() {
  echo "resume: SIGKILL mid-iteration, restart, no manual repair"
  local d; d="$(mktemp -d)"; build_fixture "$d" || { bad "could not build the fixture"; return; }
  touch "$d/.fixture/slow"      # iteration 4 writes half of Phase 3's artifacts, then sleeps
  set -m
  ( cd "$d" && CARD=0 REF_PY=./env/bin/python3 PORT_LOOP_CLAUDE="$d/.fixture/agent.sh" \
      bash "$SKILL/run.sh" --unattended --model-name minifold ) > "$d/loop1.log" 2>&1 &
  local lp=$!
  set +m
  local i=0
  while [ $i -lt 180 ]; do
    [ -f "$d/notes/eval_set.txt" ] && break
    sleep 1; i=$((i + 1))
  done
  if [ ! -f "$d/notes/eval_set.txt" ]; then bad "the loop never reached the fourth iteration"; kill -9 -"$lp" 2>/dev/null; rm -rf "$d"; return; fi
  kill -9 -"$lp" 2>/dev/null
  wait "$lp" 2>/dev/null
  if grep -q 'LOOP ENDED' "$d/loop1.log"; then bad "the loop ended on its own; the kill proved nothing"; fi
  ok "killed at iteration $(iters "$d/loop1.log"), Phase 3 half written"
  # Half of Phase 3 is on disk and no phase is green past 3. Restart with the same command.
  rm -f "$d/.fixture/slow"
  run_loop "$d" "$d/loop2.log"; local rc=$?
  want "exit code after restart" "$rc" 0
  if grep -q 'gate baseline read from' "$d/loop2.log"; then
    ok "read the frozen baseline back instead of re-freezing whatever it found"
  else bad "re-baselined the gate on restart, which would launder a tamper across a kill"; fi
  if grep -q 'LOOP-ENDED: TAMPER' "$d/loop2.log"; then bad "a kill was mistaken for a tamper"; fi
  local first; first="$(sed -n 's/^ALL-PHASES: \([0-9]*\)\/8 PASS$/\1/p' "$d/loop2.log" | head -1)"
  want "picked up where it stopped rather than from zero" "$first" 3
  rm -rf "$d"
}

case "$MODE" in
  mechanics) leg_mechanics ;;
  tamper)    leg_tamper ;;
  stall)     leg_stall ;;
  resume)    leg_resume ;;
  all)       leg_mechanics; echo; leg_tamper; echo; leg_stall; echo; leg_resume ;;
esac

echo
if [ "$FAIL" -eq 0 ]; then echo "loop selftest: every leg passed"; exit 0; fi
echo "loop selftest: a leg failed. The loop is the customer's only interface, so fix it here."
exit 1
